### ISSUE TITLE
No User-password attribute found

### ISSUE THREAD

**Issue by pwldp** [retailnext/node-radius#15]
Hi,
I try to use node-radius with MSM720 controller and I configured WPA (WPA2/AES/CCMP) wireless protection.
When MSM720 connect to node-radius there is no ```User-password``` attribute in decoded package data.

What should I do to get password from received packet?

**Comment by psanford** [comment]
Currently node-radius only supports PAP authentication. If you don't see the `User-Password` attribute that means that the MSM720 is configured to use some other type of authentication protocol like CHAP or MS-CHAPv2. If you are using WPA enterprise, then that will be further encapsulated inside an EAP message (see rfc3579). You can check to see if the radius packets have the EAP-Message attribute set.

We've not had any need to support CHAP or MS-CHAPv2. We would be happy to take a pull request to add support for one or both of these.

Supporting EAP will be a much larger endeavor. EAP is big enough that it deserves its own package (external to node-radius). Depending on how it worked, it might be reasonable to have hooks in node-radius to hand off authentication to an external EAP package.

**Comment by pwldp** [comment]
I use WPA-Enterprise with MS-CHAPv2 and I thought it will be easier to run using Node. Alternative to me is to setup Windows server with AD which is compatible with MSM720. This solution is faster.

I can see that implement WPA-Enterprise is a more complex problem. I haven't time and knowledge to do that, but I can participate in tests if someone will implement this feature.

**Comment by exculibar** [comment]
I use node-radius and node-chap made a simple project which supported PAP / CHAP / MSCHAPv1 / MSCHAPv2  authentication.

[https://github.com/exculibar/nadius](url)
