### ISSUE TITLE
Error when using EAP-Message package

### ISSUE THREAD

**Issue by anvnguyen** [retailnext/node-radius#17]
I want to add EAP-Message attribute to the response package, like this

var response = radius.encode_response({
      packet: packet,
      code: code,
      secret: "shared_secret",
      attributes: [
	    ['User-Name', username],
	    ['EAP-Message', 555, 
	    	[
	    		['Code', 1],
	    		['Id', ''],
	    		['Length', ''],
	    		['Type', 'MD5-Challenge'],
	    		['Type-Data', token],
	    	]
	    ]
	  ]
    });

Radius module throws an error
Documents/radius/node_modules/radius/lib/radius.js:277
  throw err;
        ^
Error: encode: must provide Buffer for attribute 'EAP-Message'

How to solve this issue? Thank you

**Comment by psanford** [comment]
It looks like you haven't loaded a dictionary that defines EAP-Message. Without a dictionary the library doesn't know how to encode the attribute value, so it expects you to pass it a buffer with the value properly encoded.

According to rfc2869 EAP-Message is just a string field of the EAP packet content. Encoding EAP packets is outside the scope of this library; you will need to encode the EAP packet yourself before adding it to the radius packet.
