### ISSUE TITLE
attribute class limit 8 groups

### ISSUE THREAD

**Issue by ZeevM3** [retailnext/node-radius#18]
i can't put in one attribute more than 8 strings.
for example:
Trying to insert over 8 groups(strings) into 'class' attribute results in a crash claiming it is out of boundaries.

How do i bypass this?

**Comment by Freundschaft** [comment]
how are you putting the string into the class attribute?

**Comment by ZeevM3** [comment]
grps = new Buffer(JSON.stringify({
                                groups: results.groups.map(function (elem) {
                                    return elem.cn;
                                })
                            },null,4));
                response = radius.encode_response({
                    packet: packet,
                    code: code,
                    secret: config.secret,
                    attributes: [
                        ['Class', grps]
                    ]
                });

**Comment by psanford** [comment]
Most likely your json string is > 253 bytes when you are using > 8 entries. As per https://tools.ietf.org/html/rfc2865#page-46 the maximum value of a string attribute is 253 bytes.

**Comment by ZeevM3** [comment]
@psanford 
I guess that's the case. but how can i bypass it?
regarding the class attribute, how can i insert 254+ strings? can i add more Class?

**Comment by muirrn** [comment]
You could encode each string as a separate attribute:

```
attributes: [
  ["Class", "string1"],
  ["Class", "string2"]
       ...
]
```

Then each one has the 253 length limit. This obviously will change the format of the attributes, so the receiver of this packet will have to deal with it differently.
