### ISSUE TITLE
mikrotik radius dictionary

### ISSUE THREAD

**Issue by ghost** [retailnext/node-radius#2]
I'm trying to use this:
http://wiki.mikrotik.com/wiki/Manual:RADIUS_Client/vendor_dictionary
together with all the dictionary.rfcXXX files inside the dictionaries folder provided with this repository but I have some problems and not fields seems to be loaded correctly.
If I strip out the BEGIN-VENDOR and END-VENDOR the attributes are loaded but are misunderstood by the library. Are there any issues reading files with EOL in CRLF and not only LF?

**Comment by rodrigoadachi** [comment]
I was having trouble adding the Mikrotik-Rate-Limit had the following error:

Error: encode: invalid attributes - must give Buffer for unknown attribute "Mikrotik-Rate-Limit '

Dai looked where he was looking for these values, was where I saw a small piece of code that our psanford friend posted here:

radius.add_dictionary ('mikrotik.dict');

Dai only created a mikrotik.dict file and added the entire contents of the link below
http://wiki.mikrotik.com/wiki/Manual:RADIUS_Client/vendor_dictionary

Thank you friends
