### ISSUE TITLE
How to implement ms-chapv2 authentication?

### ISSUE THREAD

**Issue by jacky810124** [retailnext/node-radius#27]
Remote server allow authentication with ms-chapv2 only, can I implement ms-chapv2 by myself? or any idea?

**Comment by psanford** [comment]
MS-CHAPv2 is an inner authentication protocol used inside a EAP/PEAP message. So you would need to implement both the outer EAP protocol and the inner MS-CHAPv2 protocol.

EAP is complicated enough that this would probably be a significant undertaking. I do believe that someone with enough motivation and persistence should be able to make it work. 

The EAP message is contained in standard radius attributes so I would suggest that implement most of the EAP logic in a separate library. You might need to make some changes to node-radius to add RFC3579 specific attribute values like 'EAP-Response'.

**Comment by jacky810124** [comment]
I got it, thank you!
