### ISSUE TITLE
WPA-2 enterprise support

### ISSUE THREAD

**Issue by haryshwaran** [retailnext/node-radius#29]
Nice work on this library, it has saved me considerable effort, thank you! I used this with captive portal and was able to get this working with little effort. Now I plan to use this package with WPA2 enterprise and looking at the logs of free radius, the peer I tested with appears to use PEAP over TLS. I just started with WPA 2, I tried to accept all WPA2 requests by sending a blind Access Accept using node-radius and nothing happened ( the peer did not connect ). It looks like I have to implement the EAP challenge response mechanism, is my assumption correct? It appears to be a heavily involved process, nevertheless, I plan to work on it over next 3 - 6 months. Any pointers would be very helpful, TIA.

**Comment by psanford** [comment]
Great to hear that someone is willing to take on this challenge!

You are correct that you will need to implement the EAP protocol. The EAP message is contained in standard radius attributes so I would suggest that implement most of the EAP logic in a separate library. You might need to make some changes to node-radius to add RFC3579 specific attribute values like 'EAP-Response'.

**Comment by gjongenelen** [comment]
@haryshwaran , did you make any progress on this?

**Comment by simllll** [comment]
@gjongenelen 
I have an initial draft of a radius server for gsuite ldap auth now, but one problem is left with the  MS-MPPE-Send-Key and MS-MPPE-Recv-Key... I will let you know if I can solve it :)
