### ISSUE TITLE
authenticate against mongoDB

### ISSUE THREAD

**Issue by dfogbel** [retailnext/node-radius#30]
I really like node-radius and will like to implement it in my project which uses MongoDB for user information storage. Who can help to make library authenticate user by looking up the DB and assigning i.e. IP based on the pre-configuration for this user. 
Happy to compensate please feel free to get in touch for further clarification.
delsonn@hotmail.com

**Comment by psanford** [comment]
This is not a forum for soliciting work. Please keep issues here directly related to bugs in node-radius.
