### ISSUE TITLE
Using with hostapd

### ISSUE THREAD

**Issue by luandro** [retailnext/node-radius#38]
I'm trying to create a RADIUS server to run in my Raspberry Pi using [hostapd]() to create the Access Point.

Should I be able to create a wifi hotspot by using this library for the RADIUS server, a data storage, hostapd and [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html)?

**Comment by psanford** [comment]
This library supports radius with PAP authentication. So if the stack you have described support that then it will probably work.

**Comment by luandro** [comment]
Could you give me example of what stack could be used in order to create a [captive portal](https://en.wikipedia.org/wiki/Captive_portal) with this library?

What exactly listens to when a new user connects to the access point, and sends the packet to port 1812?

**Comment by pihomeserver** [comment]
Hello 
You can use this one : https://github.com/pihomeserver/Kupiki-Hotspot-Script
