### ISSUE TITLE
Packet identifier number

### ISSUE THREAD

**Issue by sizovilya** [retailnext/node-radius#40]
I working on system which allows sends multiple radius requests as parallel. Number of requests may be greater then 255. But i dont know how to realize it now.  I need something like a query for requests. 

Can i insert in 'identifier' field something like uuid or guid ?

**Comment by psanford** [comment]
The identifier field for a radius packet is only 1 byte. See  https://tools.ietf.org/html/rfc2865 section 3 for details:

"The Identifier field is one octet, and aids in matching requests
      and replies.  The RADIUS server can detect a duplicate request if
      it has the same client source IP address and source UDP port and
      Identifier within a short span of time."

The identifier only needs to be unique for a specific ip:port pair. If you need to handle more than 255 concurrent in flight requests from a single device you can use multiple ports.

**Comment by sizovilya** [comment]
@psanford thank you for response.
I use next schema:
UI(gw) --> Node.js --> Remote Radius Server.
I think, if node.js server will receive any parallel requests from UI and will send this requests to remote radius, im not have guarantee for right response ordering to clients, right ? Client B, by default, can get UDP packet which intended for Client A, right ? Is it not realized on system\package level and i must realize it myself, right ? Or with 'identifier' parameter it works automatically ?

**Comment by psanford** [comment]
I don't think I have enough information to answer your question. Are you using node-radius as a client, a
server or both?

**Comment by sizovilya** [comment]
@psanford only as a client.

**Comment by psanford** [comment]
One simple solution would be to use a different udp port (making a new udp socket object) for each request. On the udp socket you can call .bind(0) which will bind to a random available port. Then you don't need to track the packets by the identifier field since you know that each socket will only be used to send 1 packet.

```

**Comment by sizovilya** [comment]
@psanford
I think it very fast, but not good solution, because all ports should be opened.
Okey, i understand. I need simple requests query mechanism.

Thank you !
