### ISSUE TITLE
Attributes without a tag have one after decoding

### ISSUE THREAD

**Issue by stffabi** [retailnext/node-radius#45]
If a packet contains an attribute with a tag all following attributes have also the same tag, even if these attributes have no tag accordingly to the radius RFC.

The problem is caused by the fact, that the `tag` variable is not reset if no `has_tag` element is found in the `attr_inf`, [see here](https://github.com/retailnext/node-radius/blob/master/lib/radius.js#L466). Therefore the tag is applied to all following attributes as long as no attribute with a has_tag and no specified tag is found.

**Comment by psanford** [comment]
Thanks for the bug report! I've pushed a fix for this issue and published a new version of the package to npm.

**Comment by stffabi** [comment]
Great, thanks so much.
