### ISSUE TITLE
Session-Timeout not working

### ISSUE THREAD

**Issue by reigelgallarde** [retailnext/node-radius#49]
I'm using the example and added `Session-Timeout` on Access-Accept.  
I'm logged in but there's no time limit.
I'm using Mikrotik Hap Lite
```
packet.attributes['Session-Timeout'] = 300;
var response = radius.encode_response({
    packet: packet,
    code: code,
    secret: secret
  });
```

Any clue?

**Comment by muirrn** [comment]
To specify additional attributes to `encode_response` you should pass `attributes` to `encode_response`. See https://github.com/retailnext/node-radius#radiusencode_responseargs

```
var response = radius.encode_response({
  packet: packet,
  code: code,
  secret: secret,
  attributes: [
    ["Session-Timeout", 300],
  ]
});
```

**Comment by reigelgallarde** [comment]
an `aha moment`! thanks
