### ISSUE TITLE
sending PEAP responses

### ISSUE THREAD

**Issue by jwestbrook** [retailnext/node-radius#52]
Just registering an issue for future consideration.

While implementing PEAP Authentication I ran into an issue:
```
TypeError: "value" argument is out of bounds
    at Object.Radius.encode_attributes (/opt/radius_server/node_modules/radius/lib/radius.js:875:12)
```

I was able to debug it and figured that I shouldnt be attempting to send a 1499 byte PEAP response that includes a SSL cert in an attribute value that only supports 255 bytes.

That being said, doing a sanity check that the attribute value length is greater than what is supported and telling the user it doesnt fit would be helpful.

In this instance the TLS message CAN be sent in 253 byte fragments so I'll be breaking it up and sending it that way.

**Comment by psanford** [comment]
Thanks for the issue! I agree that a sanity check on the attribute length makes sense.

Want to send a pull request?

**Comment by psanford** [comment]
I'm going to close this since there hasn't been any activity on this issue in months. If someone wants to add this sanity check please send a PR.
