### ISSUE TITLE
There is no password attr

### ISSUE THREAD

**Issue by samialmorshedi** [retailnext/node-radius#54]
This is all data I get in a request:
```
{ 'Service-Type': 'Framed-User',
  'Framed-Protocol': 'PPP',
  'NAS-Port': 666,
  'NAS-Port-Type': 'Virtual',
  'User-Name': 'test',
  'Calling-Station-Id': '2.2.2.20',
  'Called-Station-Id': '2.2.2.2',
  'Vendor-Specific': {},
  'NAS-Identifier': 'MikroTik',
  'NAS-IP-Address': '3.3.3.3.' }
```

IP addresses are fake here. why I could not get password from microtik?

**Comment by psanford** [comment]
Presumably you are not seeing the User-Password attribute because your microtik device isn't sending it in that packet. It looks like the output you provided is only the `packet.attributes`. What is the `packet.code` value you are getting?

**Comment by samialmorshedi** [comment]
Here you are @psanford 
```
code: 'Access-Request',
  identifier: 124,
  length: 182,
  authenticator: <Buffer 85 46 05 4a d6 47 fa d6 f8 88 31 60 6a 6d d4 1c>,
  attributes: .....
```

**Comment by psanford** [comment]
It looks like your microtik device isn't configured to use PAP authentication.

**Comment by samialmorshedi** [comment]
@psanford how can I do it?
![Capture](https://user-images.githubusercontent.com/30777032/73119359-f60d1f00-3f75-11ea-82e2-3f07dd2ad18e.jpg)

**Comment by psanford** [comment]
Sorry, I'm unfamiliar with the software you are using. Perhaps you should contact the developers of that software for support.

**Comment by samialmorshedi** [comment]
@psanford Seems you are the main contribute in this project! Who should I send this ticket to?

The image I sent is Mikrotik settings.

**Comment by psanford** [comment]
I'm sorry if I was unclear. I am not familiar with the Mikrotik software you are using so I'm not going to be able to help you configure that. Perhaps the maintainers of the Mikrotik software can assist you.

I don't think there is an issue here with the node-radius library. If you have pcap file that shows there is something misbehaving in this library we can investigate further.
