### ISSUE TITLE
User-Password is not defined in my packet.

### ISSUE THREAD

**Issue by dfrossouw** [retailnext/node-radius#57]
Everytime I send a message to the server `password = packet.attributes['User-Password'];` remains undefined and I get a 'Access-Reject' because I cannot authenticate.

**Comment by psanford** [comment]
Can you provide a minimal example that demonstrates the problem?

**Comment by psanford** [comment]
(I should have mentioned) `User-Password` will only be present if you are using PAP for your authentication method. Other authentication methods do not have built in support in node-radius (like CHAP, MS-CHAPv2, EAP). So if you are using a non-PAP authentication method you will need to write additional code to handle that yourself.

**Comment by dfrossouw** [comment]
`{ address: '192.168.15.5', family: 'IPv4', port: 39615, size: 144 }
{
  code: 'Access-Request',
  identifier: 21,
  length: 144,
  authenticator: <Buffer d9 60 9c 71 de 31 00 1e 09 6c ae 8a f9 05 04 55>,
  attributes: {
    'Service-Type': 'Framed-User',
    'Framed-MTU': 1400,
    'User-Name': 'daniel',
    'NAS-Port-Id': 'radius',
    'NAS-Port-Type': 'Wireless-802.11',
    'Calling-Station-Id': '9A-77-74-65-D7-ED',
    'Called-Station-Id': 'C6-AD-34-82-83-8F:radius',
    'EAP-Message': <Buffer 02 00 00 0b 01 64 61 6e 69 65 6c>,
    'Message-Authenticator': <Buffer 21 8c 3d 59 7d bb 1f b6 48 83 db fd 9b 89 e4 bb>,
    'NAS-Identifier': 'MK-EMP',
    'NAS-IP-Address': '192.168.15.5'
  },
  raw_attributes: [
    [ 6, <Buffer 00 00 00 02> ],
    [ 12, <Buffer 00 00 05 78> ],
    [ 1, <Buffer 64 61 6e 69 65 6c> ],
    [ 87, <Buffer 72 61 64 69 75 73> ],
    [ 61, <Buffer 00 00 00 13> ],
    [ 31, <Buffer 39 41 2d 37 37 2d 37 34 2d 36 35 2d 44 37 2d 45 44> ],
    [
      30,
      <Buffer 43 36 2d 41 44 2d 33 34 2d 38 32 2d 38 33 2d 38 46 3a 72 61 64 69 75 73>
    ],
    [ 79, <Buffer 02 00 00 0b 01 64 61 6e 69 65 6c> ],
    [ 80, <Buffer 21 8c 3d 59 7d bb 1f b6 48 83 db fd 9b 89 e4 bb> ],
    [ 32, <Buffer 4d 4b 2d 45 4d 50> ],
    [ 4, <Buffer c0 a8 0f 05> ]
  ]
}`

**Comment by psanford** [comment]
Your payload has an `EAP-Message` field which suggests that the radius client is configured to use EAP instead of PAP. node-radius is unlikely to ever support EAP messages directly but we'd be happy if someone else implemented an external EAP package that could work with node-radius.

See also #7 #15 #17 #29
